frontend:
  - changed-files:
      - any-glob-to-any-file: 'client/**'

backend:
  - changed-files:
      - any-glob-to-any-file: 'server/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - '.github/**'
